"""Future-only migration retains exact history and fails closed after interruption."""

import fcntl
import json
from pathlib import Path

import pytest

from scripts.changerail import executor_binding as binding
from scripts.changerail import release_executor as release
from scripts.changerail import engine_snapshot as snapshot
from scripts.changerail import local_delivery as d
from test_release_executor_integration import full_release as full_release, put, git


def test_initial_preview_apply_idempotence_and_exact_history(full_release):
    project, engine, _ = full_release
    run = put(
        project,
        ".runtime/changerail/runs/old/run.json",
        '{"finished_at":"2026-01-01T00:00:00Z","reviews_used":2,"remaining_budget":17}\n',
    )
    counter = put(
        project,
        ".runtime/changerail/runs/old/review-budget.json",
        '{"used":2,"repair_remaining":17}\n',
    )
    original = {p: p.read_bytes() for p in (run, counter)}
    preview = binding.prepare(project, engine, dry_run=True)
    assert not Path(preview["proposal"]).exists()
    assert not (project / release.BINDING).exists()
    proposal = binding.prepare(project, engine)
    path = Path(proposal["proposal"])
    assert path == Path(preview["proposal"])
    assert binding.apply(path, dry_run=True)["state"] == "preview"
    first = binding.apply(path)
    assert binding.apply(path) == first
    assert {p: p.read_bytes() for p in original} == original
    assert list((project / ".runtime/changerail/runs").iterdir()) == [run.parent]
    assert (path.parent / "intent.json").is_file()
    assert (path.parent / "applied.json").is_file()


def test_snapshot_migration_requires_existing_exact_identity_and_retains_old_bytes(
    full_release, tmp_path
):
    project, engine, _ = full_release
    sealed = tmp_path / "snapshot"
    snapshot.create_snapshot(engine, sealed)
    previous = snapshot.bind_engine(project, sealed)
    original = (project / release.BINDING).read_bytes()
    for identity in (None, "wrong"):
        with pytest.raises(ValueError, match="previous.identity|previous identity"):
            binding.prepare(project, engine, previous_identity=identity)
    value = binding.prepare(
        project, engine, previous_identity=previous["engine_identity"]
    )
    assert bytes.fromhex(value["before"][release.BINDING]["bytes"]) == original
    binding.apply(Path(value["proposal"]))
    assert (
        release.document(project / release.BINDING)["schema"] == release.BINDING_SCHEMA
    )
    with pytest.raises(
        snapshot.EngineSnapshotError, match="invalid project engine binding"
    ):
        snapshot.verify_binding(project)
    # Returning to the snapshot is another explicit transaction, not file restore.
    back = binding.prepare(
        project, sealed, kind="snapshot", previous_identity=value["identity"]
    )
    binding.apply(Path(back["proposal"]))
    assert snapshot.verify_binding(project) == previous


def test_unavailable_snapshot_cannot_be_inferred_from_binding(full_release, tmp_path):
    project, engine, _ = full_release
    put(
        project,
        release.BINDING,
        json.dumps(
            {
                "schema": snapshot.BINDING_SCHEMA,
                "project_root": str(project),
                "engine_root": str(tmp_path / "missing"),
                "engine_identity": "known-string",
            }
        ),
    )
    with pytest.raises((ValueError, OSError)):
        binding.prepare(project, engine, previous_identity="known-string")
    assert not (project / binding.TRANSACTIONS).exists()


@pytest.mark.parametrize("name", [release.BINDING, ".changerail/chrl"])
def test_before_drift_is_rejected_without_overwrite(full_release, name):
    project, engine, _ = full_release
    value = binding.prepare(project, engine)
    path = put(project, name, "unrelated")
    with pytest.raises(ValueError, match="expected before"):
        binding.apply(Path(value["proposal"]))
    assert path.read_text() == "unrelated"
    assert not (Path(value["proposal"]).parent / "intent.json").exists()


@pytest.mark.parametrize(
    "case", ["tracked", "unknown", "source", "verification", "history"]
)
def test_unsafe_project_states_are_refused(full_release, case):
    project, engine, _ = full_release
    if case == "tracked":
        put(project, ".changerail/chrl", "tracked")
        git(project, "add", "-f", ".changerail/chrl")
    elif case == "unknown":
        put(
            project,
            ".changerail/chrl",
            "#!/bin/sh\n# Generated by ChangeRail executor-binding v1.\n",
            0o755,
        )
    elif case == "source":
        put(project, ".changerail/source-link.json", "{}")
    elif case == "verification":
        put(
            project,
            ".runtime/changerail/runs/old/verification-attempts/a.json",
            '{"state":"started"}',
        )
    else:
        value = binding.prepare(project, engine)
        put(project, ".runtime/changerail/runs/old/review-budget.json", '{"used":2}')
        with pytest.raises(ValueError, match="history changed"):
            binding.apply(Path(value["proposal"]))
        return
    with pytest.raises(ValueError):
        binding.prepare(project, engine)
    assert not (project / release.BINDING).exists()


@pytest.mark.parametrize("boundary", ["launcher", "binding", "applied"])
def test_crash_reconciles_only_exact_intent_without_resetting_old_runs(
    full_release, monkeypatch, boundary
):
    project, engine, _ = full_release
    run = put(
        project,
        ".runtime/changerail/runs/unfinished/run.json",
        '{"execution_contract":"changerail.native.v1","mode":"delivery","lifecycle_mode":"openspec-v1","finished_at":null,"reviews_used":2,"process_identity":{"engine/identity":"old"}}',
    )
    original = run.read_bytes()
    value = binding.prepare(project, engine)
    path = Path(value["proposal"])
    replace, append = binding._replace, binding._append

    def interrupted_replace(project, name, state):
        replace(project, name, state)
        if (boundary == "launcher" and name == ".changerail/chrl") or (
            boundary == "binding" and name == release.BINDING
        ):
            raise OSError("fixture crash")

    def interrupted_append(path, value):
        if boundary == "applied" and path.name == "applied.json":
            raise OSError("fixture crash")
        append(path, value)

    monkeypatch.setattr(binding, "_replace", interrupted_replace)
    monkeypatch.setattr(binding, "_append", interrupted_append)
    with pytest.raises(OSError, match="fixture crash"):
        binding.apply(path)
    with pytest.raises(ValueError, match="pending"):
        binding.ensure_no_pending(project)
    import subprocess

    blocked = subprocess.run(
        [str(project / ".changerail/chrl"), "--engine-root"],
        capture_output=True,
        text=True,
    )
    assert blocked.returncode == 2
    assert "pending executor binding" in blocked.stderr
    monkeypatch.setattr(binding, "_replace", replace)
    monkeypatch.setattr(binding, "_append", append)
    assert binding.apply(path, reconcile=True)["state"] == "applied"
    assert (path.parent / "reconciled.json").exists()
    assert run.read_bytes() == original
    monkeypatch.setattr(d, "REPO_ROOT", project)
    monkeypatch.setattr(d, "RUNTIME_ROOT", project / ".runtime/changerail")
    monkeypatch.setattr(
        d, "execution_identity", lambda: {"engine/identity": value["identity"]}
    )
    with pytest.raises(d.DeliveryError, match="frozen execution process changed"):
        d.require_frozen_execution(run.parent)


def test_project_and_binding_lock_order_excludes_concurrent_writers(full_release):
    project, engine, _ = full_release
    for name in (
        ".runtime/changerail/delivery.lock",
        ".changerail/.engine-binding.lock",
    ):
        path = put(project, name, "")
        with path.open("r+") as stream:
            fcntl.flock(stream.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
            with pytest.raises(ValueError, match="holds|writer"):
                binding.prepare(project, engine)
        assert not (project / release.BINDING).exists()


def test_live_session_blocks_binding_before_apply(full_release):
    import os
    import subprocess

    project, engine, _ = full_release
    proposal = binding.prepare(project, engine)
    child = subprocess.Popen(
        ["/usr/bin/python3", "-I", "-S", "-c", "print('ready',flush=True);input()"],
        env={
            **os.environ,
            "CHRL_RUN_DIR": str(project / ".runtime/changerail/runs/live"),
        },
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        text=True,
    )
    try:
        assert child.stdout.readline().strip() == "ready"
        with pytest.raises(ValueError, match="live process"):
            binding.apply(Path(proposal["proposal"]))
        assert not (project / release.BINDING).exists()
    finally:
        child.communicate("done\n", timeout=10)


def test_distribution_cannot_attach_source_over_executor_binding(full_release):
    import distribution as dist

    project, engine, _ = full_release
    value = binding.prepare(project, engine)
    binding.apply(Path(value["proposal"]))
    before = (project / release.BINDING).read_bytes()
    assert (
        dist.main(["attach", str(project), "--source", str(engine), "--dry-run"]) == 2
    )
    assert (project / release.BINDING).read_bytes() == before
    assert not (project / ".changerail/source-link.json").exists()


def test_malformed_terminal_verification_is_not_proof_of_quiescence(full_release):
    project, engine, _ = full_release
    put(
        project,
        ".runtime/changerail/runs/old/verification-attempts/a.json",
        json.dumps(
            {
                "schema": "changerail.verification-attempt-intent.v1",
                "state": "observed_terminal",
                "outcome": "exit",
                "finished_at": "unknown",
            }
        ),
    )
    with pytest.raises(ValueError, match="unresolved verification"):
        binding.prepare(project, engine)


def test_cli_fence_precedes_redirect_to_old_snapshot_after_launcher_crash(
    full_release, tmp_path, monkeypatch
):
    import subprocess
    import os

    project, engine, _ = full_release
    old_source = tmp_path / "old-source"
    git(engine, "clone", "--no-hardlinks", str(engine), str(old_source))
    git(old_source, "config", "user.name", "Fixture")
    git(old_source, "config", "user.email", "fixture@example.invalid")
    # A sealed pre-feature snapshot intentionally has no pending-binding guard.
    put(
        old_source,
        "scripts/changerail/engine_runtime.py",
        "print('OLD_SNAPSHOT_EXECUTED')\n",
    )
    put(old_source, "bin/chrl", "#!/bin/sh\necho OLD_SNAPSHOT_EXECUTED\n", 0o755)
    git(old_source, "add", "scripts/changerail/engine_runtime.py", "bin/chrl")
    git(old_source, "commit", "-qm", "isolated pre-feature engine")
    sealed = tmp_path / "old-snapshot"
    snapshot.create_snapshot(old_source, sealed)
    previous = snapshot.bind_engine(project, sealed)
    before = (project / release.BINDING).read_bytes()
    proposal = binding.prepare(
        project, engine, previous_identity=previous["engine_identity"]
    )
    replace = binding._replace

    def crash(project, name, state):
        replace(project, name, state)
        if name == ".changerail/openspec":
            raise OSError("crash before final binding")

    monkeypatch.setattr(binding, "_replace", crash)
    with pytest.raises(OSError, match="crash before final binding"):
        binding.apply(Path(proposal["proposal"]))
    assert (project / release.BINDING).read_bytes() == before
    for argv in (
        [str(project / ".changerail/chrl"), "--engine-root"],
        [str(project / ".changerail/openspec"), "--version"],
        [str(engine / "bin/chrl"), "--project", str(project), "--engine-root"],
        [str(engine / "bin/openspec"), "--project", str(project), "--version"],
    ):
        result = subprocess.run(argv, capture_output=True, text=True, timeout=5)
        assert result.returncode != 0, argv
        assert "pending executor binding" in result.stderr
        assert "OLD_SNAPSHOT_EXECUTED" not in result.stdout
    direct = subprocess.run(
        [
            "/usr/bin/python3",
            "-B",
            "-P",
            "-m",
            "scripts.changerail.engine_runtime",
            "--engine-root",
        ],
        env={
            **os.environ,
            "PYTHONPATH": str(engine),
            "CHRL_PROJECT_ROOT": str(project),
        },
        cwd=project,
        capture_output=True,
        text=True,
        timeout=5,
    )
    assert direct.returncode != 0
    assert "pending executor binding" in direct.stderr
    monkeypatch.setattr(binding, "_replace", replace)
    binding.apply(Path(proposal["proposal"]), reconcile=True)
    result = subprocess.run(
        [str(project / ".changerail/chrl"), "--engine-root"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == str(engine)
    # Restoring the old file is never the reverse transition API.
    assert snapshot.verify_snapshot(sealed)


def test_applied_binding_retry_allows_new_history_without_rewriting_it(full_release):
    project, engine, _ = full_release
    old = put(project, ".runtime/changerail/runs/old/run.json", '{"reviews_used":2}\n')
    prepared = binding.prepare(project, engine)
    proposal = Path(prepared["proposal"])
    first = binding.apply(proposal)
    new = put(
        project,
        ".runtime/changerail/runs/new/run.json",
        '{"finished_at":"2026-09-12T00:00:00Z","reviews_used":1}\n',
    )
    before = {path: path.read_bytes() for path in (old, new, project / release.BINDING)}
    assert binding.apply(proposal) == first
    assert all(path.read_bytes() == data for path, data in before.items())
    old.write_text('{"reviews_used":0}')
    with pytest.raises(ValueError, match="original retained history"):
        binding.apply(proposal)


def test_public_ignore_permits_generated_launchers_without_tracking(full_release):
    from test_release_executor_integration import SOURCE

    project, engine, _ = full_release
    (project / ".gitignore").write_bytes((SOURCE / ".gitignore").read_bytes())
    prepared = binding.prepare(project, engine, dry_run=True)
    assert prepared["dry_run"]
    for name in (release.BINDING, *binding.LAUNCHERS):
        assert git(project, "check-ignore", "--", name) == name
        assert not git(project, "ls-files", "--", name)
